alter table app_settings
  add column if not exists private_fm_api_key text not null default '';

alter table ai_digest_configs
  add column if not exists private_fm_enabled boolean not null default false;

create table if not exists private_fm_episodes (
  id bigint generated by default as identity primary key,
  article_id bigint not null references articles(id) on delete cascade,
  run_id bigint not null references ai_digest_runs(id) on delete cascade,
  status text not null,
  script_text text null,
  audio_paths text[] not null default '{}'::text[],
  tts_model text null,
  voice text null,
  response_format text null,
  error_code text null,
  error_message text null,
  job_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint private_fm_episodes_status_check check (
    status in ('queued', 'running', 'script_ready', 'succeeded', 'failed')
  )
);

create unique index if not exists private_fm_episodes_article_unique
  on private_fm_episodes(article_id);

create index if not exists private_fm_episodes_run_id_idx
  on private_fm_episodes(run_id);
