-- 批量写回的目标和结果持久化保存，页面关闭或 Worker 重启不会丢失进度。
create table fever_batch_read_runs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  feed_id bigint null,
  local_updated_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, id)
);
create index fever_batch_read_runs_user_created_idx on fever_batch_read_runs(user_id, id desc);

create table fever_batch_read_items (
  user_id bigint not null references users(id) on delete cascade,
  run_id bigint not null,
  article_id bigint not null,
  article_title text not null,
  fever_account_id bigint not null,
  fever_item_id text not null,
  status text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed')),
  attempt integer not null default 1 check (attempt > 0),
  error_message text null,
  updated_at timestamptz not null default now(),
  primary key (user_id, run_id, article_id),
  foreign key (user_id, run_id) references fever_batch_read_runs(user_id, id) on delete cascade
);
-- 不依赖文章和账号外键：来源被删除后仍保留失败项，并在执行时重新校验归属及有效性。
create index fever_batch_read_items_run_status_idx on fever_batch_read_items(user_id, run_id, status);
